language: python
python:
  - 3.8.2
services:
  - postgresql
addons:
  postgresql: '10'
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate --noinput
install:
  - cp contrib/env-sample .env
  - unset DATABASE_URL
  - export DATABASE_URL=postgres://postgres@localhost/travisci
  - pip install pip -U
  - pip install -r requirements.txt
  - pip install pytest pytest-django flake8 # These are development dependencies
script:
  - flake8
  - pytest