dist: xenial
language: python
python:
  - 3.8.2
services:
  - docker
install:
  - cp contrib/env-sample .env
  - pip install pip -U pip
  - pip install -r requirements.txt
  - pip install pytest pytest-django flake8 # These are development dependencies
before_script:
  - docker-compose -f Docker-compose up -d
  - python manage.py migrate
script:
  - flake8
  - pytest